

#         Powered by TabooLib 5.0         #


name: ${name}
main: ${main}
version: ${version}
authors:
  - Bkm016
soft-depend:
  - Citizens
  - Shopkeeper
  - MythicMobs
  - Skript
  - SkillAPI
  - WorldEdit
  - WorldGuard
  - PlaceholderAPI
  - Vault
  - SacredItem
  - PurtmarsItem


lib-version: ${libVersion}
api-version: 1.13